name: superpoint
channels:
  - pytorch
  - defaults
dependencies:
  - python==3.7.1
  - cudatoolkit==10.0.130
  - pytorch==1.1.0
  - opencv==3.4.2
  - numpy==1.19.2
  - matplotlib==3.3.4
  - ipykernel == 5.3.4
